### ISSUE TITLE
[290/390-p11] Clarifying question on Intro

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#118]
Dear @kevinamstutz , the last paragraph in the "Dataset" part in the introduction section of the project says
> ... As fantastic as this database is, it would be trivial to load up the entire database in R or Python and do your analysis using `merge`-like functions. ... 

May I ask what was intended by this sentence? Also, I am not sure what "`merge`-like functions" refers to. 

Thanks in advance for your clarification!

**Comment by kevinamstutz** [comment]
Hey @ymzhang-neo, the purpose of the sentence was to explain to students that this particular database doesn't really harness the abilities of a database due to the minuscule size of the database and the fact that you could easily use functions like `merge` in r to do the joins with no real need of a database. Do you think I should rephrase things?

**Comment by ymzhang-neo** [comment]
Ah, I see! I think it a nice note for the students to know that we can load the entire `lahman` database in R or Python. 

Nevertheless, honestly, I would still suggest that we remove the paragraph for the following three reasons: (1) this project focuses on the `elections` database, (2) the questions do not include SQL joins, and (3) some students may not be familiar with `merge` in R or similar functions in Python. What do you think?

**Comment by kevinamstutz** [comment]
I totally agree! Removed in ced484b
