### ISSUE TITLE
[290-p4] Q1 File and permission

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#62]
Hi @kevinamstutz , the main issue I notice about Q1 is the permission that students have. Please see my code below and the Terminal output in the attachment.
```
date; grep -Ri "bears. beets. battlestar galactica" /class/datamine/data; date
```
Attachment: [f20-290-p4-preview-q1out.txt](https://github.com/TheDataMine/the-examples-book/files/5194371/f20-290-p4-preview-q1out.txt)

Meanwhile, there seem more than one `the_office_dialogue.csv` file under `/class/datamine/data/`:
```
/class/datamine/data/movies_and_tv/the_office_dialogue.csv
/class/datamine/data/spring2020/the_office_dialogue.csv
```
However, the path in [the solution](https://github.com/TheDataMine/fall2020-stat29000/blob/master/project04/stat29000project04solutions.Rmd)
```
/class/datamine/data/the_office/the_office_dialogue.csv
```
is not available. (I used the one under `/class/datamine/data/movies_and_tv/` for previewing.)

Could you double check the file location?

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo,

These are great catches. The output from grep should now be limited to a single file `/class/datamine/data/movies_and_tv/the_office_dialogue.csv`, and only 1 line of "error" output for the `/class/datamine/data/hidden` folder. 

I just removed the spring2020 folder csv since it is the same and we don't need that one anymore.

I also fixed the solution to have the correct location, thanks! Maybe try and run things one more time on your end to see if it looks better?

**Comment by kevinamstutz** [comment]
I think this one is fixed.

**Comment by ymzhang-neo** [comment]
Dear @kevinamstutz thank you for the fix! Yes, I got the output as you described: 
```
$ date; grep -Ri "bears. beets. battlestar galactica" /class/datamine/data; date
Wed Sep  9 15:11:26 EDT 2020
/class/datamine/data/movies_and_tv/the_office_dialogue.csv:12466,"03","21","Product Recall","Randall Einhorn","Brent Forrester;Justin Spitzer","Jim","Fact. Bears eat beets. Bears. Beets. Battlestar Galactica.","Fact. Bears eat beets. Bears. Beets. Battlestar Galactica.",8.8,2403,"2007-05-03"
grep: /class/datamine/data/hidden: Permission denied
Wed Sep  9 16:05:12 EDT 2020
```
