### ISSUE TITLE
[290-p5] Q8 quick clarification

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#77]
Hi @kevinamstutz , last post about 290 Project 5 here. Question 8 says:
> ... Based on this comparison, decide (anecdotally) whether you think people found the review helpful because the product is overrated, underrated, or correctly reviewed by the masses.

I was trying to understand the clause "because the product is overrated, underrated, or correctly reviewed by the masses". Is it okay to say the following instead?
> because the distribution of scores that the product receives.

I make this suggestion because I am not sure whether `Score` would imply something being, say, overrated. "Overrating" to me sounds like a product gets many high scores when it should be rated lower. However, based on only the `Score` column, we could not see what is the "appropriate" score for a product. Thus, I think it could be difficult to tell whether something is over- or under-rated. 

But this is just my perspective. Question 8 already explicitly asks the students to compare the histograms. So feel free to ignore this post in case I am over-thinking. Thanks!

**Comment by kevinamstutz** [comment]
Dear @ymzhang-neo, I'm happy to change the wording. The idea behind the phrasing was situations I find quite frequently on Amazon, for instance. You look at a product with a high average review. When you go to actually look at the reviews, you see some very helpful reviews that are more negative but give detailed reasons why. I'd call this overrated (even though it technically isn't the correct term). 

Same for the situation if you see a low rated product and then you go look at the reviews and the 1 star reviews are a bunch of reviews where the product came broken. Well to me, that product is underrated (potentially) as whether or not the product came broken has nothing (well not exactly _nothing_) to do with the actual quality of the product. I want to know about the product, not about whether or not some peoples came broken or they struggle with following instructions, etc. Make sense?

With that all being said, I'm going to change the wording because it is just easier and less likely to confuse. Thanks!

**Comment by kevinamstutz** [comment]
How about this @ymzhang-neo ?:

Use R to load up `reviews.csv` into a new data.frame called `dat`. Create a histogram for each products' `Score`. Compare the most helpful review `Score` with the `Score`'s given in the histogram. Based on this comparison, make draw some anecdotal conclusions about the product. For example, if a 4.5 star product has a super helpful review that gives the product 1 star, I may draw the (anecdotal) conclusion that the product is overrated.

**Comment by kevinamstutz** [comment]
Or this is better:

Use R to load up reviews.csv into a new data.frame called dat. Create a histogram for each products' Score. Compare the most helpful review Score with the Score's given in the histogram. Based on this comparison, point out some curiosities about the product that may be worth exploring. For example, if a 4.5 star product has a super helpful review that gives the product 1 star, I may tend to wonder if the product is not as great as it seems to be.

**Comment by ymzhang-neo** [comment]
Hi @kevinamstutz , thank you for sharing your thought! I definitely saw Amazon reviews of 1 star that only complained something irrelevant to the intended functionality. I now understand better the question!

I like the second version where you encourage the students to explore the curiosities! I would suggest a minor modification of the last sentence:
> For example, if a ~~4.5 star~~ product _receives many high scores, but_ has a super helpful review that gives the product 1 star, I may tend to wonder if the product is not as great as it seems to be.

I make this suggestion just in case some students would try to calculate an average score or other statistics (basically, over-thinking) for this question. What do you think?

**Comment by ymzhang-neo** [comment]
Just notice this: For the third item under "Item(s) to submit", what about the following modification?
> 1-2 sentences describing the curious pattern that you would like to further explore.

**Comment by kevinamstutz** [comment]
Hey @ymzhang-neo I think I fixed that in the recent commit, let me know!

**Comment by ymzhang-neo** [comment]
Thanks @kevinamstutz I think the question description looks nice! 

I just post a follow up suggestion above about the "Item(s) to submit" - shall we add that as well?

**Comment by kevinamstutz** [comment]
Yep! Just added it, thanks @ymzhang-neo!

**Comment by ymzhang-neo** [comment]
Thank you @kevinamstutz !
